server:
  port: 8880
  tomcat:
    uri-encoding: UTF-8

spring:
  http:
    encoding:
      charset: UTF-8
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: PORTFOLIO
    password: 51277105
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true